
global:
  # Image registry (and optional repository sub path) to use for all images
  imageRegistryPrefix: "127.0.0.1:30000"

image:
  pullPolicy: Always
  tag: "latest"

frontend:
  image:
    image: "klerk-todo/frontend"

backend:
  image:
    image: "klerk-todo/backend"
  llmServerUrl: "http://llm:11434"

backendLlm:
  image:
    image: "klerk-todo/backend-llm"

ingress:
  annotations: {}
    # cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - "klerk-todo.moshicon.se"
  tls:
    - secretName: "klerk-todo-tls"
      hosts:
        - "klerk-todo.moshicon.se"

cleanup:
  # Enable the cleanup CronJob that deletes backend pods every 24 hours to purge demo data
  enabled: true
  # Cron schedule for cleanup (default: daily at midnight)
  schedule: "0 0 * * *"
  # Number of successful jobs to keep in history
  successfulJobsHistoryLimit: 3
  # Number of failed jobs to keep in history
  failedJobsHistoryLimit: 1
