apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm
  labels:
    app.kubernetes.io/name: klerk-todo
    app.kubernetes.io/component: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: klerk-todo
      app.kubernetes.io/component: llm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: klerk-todo
        app.kubernetes.io/component: llm
    spec:
      containers:
      - name: ollama
        image: "{{ .Values.global.imageRegistryPrefix }}/{{ .Values.backendLlm.image.image}}:{{.Values.image.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
