{{- if .Values.cleanup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-cleanup
  labels:
    app.kubernetes.io/name: klerk-todo
    app.kubernetes.io/component: cleanup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-cleanup
  labels:
    app.kubernetes.io/name: klerk-todo
    app.kubernetes.io/component: cleanup
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-cleanup
  labels:
    app.kubernetes.io/name: klerk-todo
    app.kubernetes.io/component: cleanup
subjects:
- kind: ServiceAccount
  name: backend-cleanup
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: backend-cleanup
  apiGroup: rbac.authorization.k8s.io
{{- end }}
