apiVersion: v1
kind: Service
metadata:
  name: llm
  labels:
    app.kubernetes.io/name: klerk-todo
    app.kubernetes.io/component: llm
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: klerk-todo
    app.kubernetes.io/component: llm
