apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: klerk-todo
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: klerk-todo
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: klerk-todo
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: python
        image: "{{ .Values.global.imageRegistryPrefix }}/{{ .Values.backend.image.image}}:{{.Values.image.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: LLM_URL
          value: "http://llm:11434"
