apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: klerk-todo
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: klerk-todo
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: klerk-todo
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.global.imageRegistryPrefix }}/{{ .Values.frontend.image.image}}:{{.Values.image.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
